apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-user-service
  template:
    metadata:
      labels:
        app: lissa-trading-user-service
    spec:
      containers:
        - name: auth-service
          image: belaquaaa/lissa-trading-user-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/lissa-trading-db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root-password-123
            - name: SPRING_DATA_DEFAULT_SCHEMA
              value: user_service_db
            - name: AUTH_SERVICE_URL
              value: http://lissa-trading-auth-service:8081
            - name: USER_SERVICE_URL
              value: http://lissa-trading-user-service:8080
            - name: TINKOFF_API_SERVICE_URL
              value: http://lissa-trading-tinkoff-api-service:8082
