server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ${SPRING_DATA_DEFAULT_SCHEMA}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: ${SPRING_DATA_DEFAULT_SCHEMA}

logging:
  level:
    lissa.trading.user.service.aspect: INFO

security:
  internal:
    token: ${SECURITY_INTERNAL_TOKEN}

integration:
  rest:
    auth-service-url: ${AUTH_SERVICE_URL}
    user-service-url: ${USER_SERVICE_URL}
    tinkoff-api-service-url: ${TINKOFF_API_SERVICE_URL}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        exclude: '*'
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}