spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: user_service_db

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: user_service_db

logging:
  level:
    lissa.trading.user.service.aspect: INFO

integration:
  rest:
    auth-service-url: http://localhost:8081
    user-service-url: http://localhost:8080
    tinkoff-api-service-url: http://localhost:8082
  rabbit: