server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: user_service_db
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: user_service_db

security:
  internal:
    token: ZFhObGNsTmxjblpwWTJVdGFXNTBaWEp1WVd3dGEyVjU=

logging:
  level:
    lissa.trading.user.service.aspect: INFO

integration:
  rest:
    statistics-service:
      token: YzNSaGRHbHpkR2xqY3kxcGJuUmxjbTVoYkMxclpYaz0K
    auth-service-url: http://localhost:8081
    user-service-url: http://localhost:8080
    tinkoff-api-service-url: http://localhost:8082
    moex-api-service-url: http://localhost:8086
  rabbit:
    statistics-service:
      user-queue:
        name: user-stats-queue
    user-service:
      exchange:
        name: user-notifications-exchange;
      favourite-stocks-queue:
        name: favourite-stocks
        routing-key: userService.favourite-stocks
        template: "*.favourite-stocks"
      user-update-queue:
        name: user-update
        routing-key: userService.user-update
        template: "*.user-update"