server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lissa-trading-db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: user_service_db
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: user_service_db

security:
  internal:
    token: ZFhObGNsTmxjblpwWTJVdGFXNTBaWEp1WVd3dGEyVjU=

logging:
  level:
    lissa.trading.user.service.aspect: INFO

integration:
  rest:
    auth-service-url: http://localhost:8081
    services:
      tinkoff-api:
        url: http://localhost:8082
        token: ZEdsdWEyOW1aa0Z3YVMxcGJuUmxjbTVoYkMxclpYaz0K
      moex-api:
        url: http://localhost:8086
        token: Ylc5bGVFRndhUzFwYm5SbGNtNWhiQzFyWlhrPQ==
  rabbit:
    inbound:
      tg-bot:
        favourite-stocks:
          queue: tg-bot-favorite-stocks
          routing-key: tgBot.favourite-stocks
        user-update:
          queue: tg-bot-user-update
          routing-key: tgBot.user-update
    outbound:
      user-service:
        favourite-stocks:
          queue: user-service-favourite-stocks
          routing-key: userService.favourite-stocks
        user-update:
          queue: user-service-user-update
          routing-key: userService.user-update
      statistics-service:
        user:
          queue: user-stats-queue
      user-notifications:
        exchange: user-notifications-exchange
