version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lissa-trading-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  init-db:
    image: postgres:15
    container_name: init-db
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lissa-trading-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    entrypoint: /bin/bash -c "
      until pg_isready -h postgres -U $POSTGRES_USER; do
      echo 'Waiting for PostgreSQL...';
      sleep 2;
      done;
      psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /docker-entrypoint-initdb.d/init.sql;"
    restart: "no"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8089:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
