apiVersion: v1
kind: ConfigMap
metadata:
  name: lissa-trading-user-service-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://lissa-trading-db:5432/lissa-trading-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_DEFAULT_SCHEMA: "user_service_db"
  AUTH_SERVICE_URL: "http://lissa-trading-auth-service:8081"
  USER_SERVICE_URL: "http://lissa-trading-user-service:8080"
  TINKOFF_API_SERVICE_URL: "http://lissa-trading-tinkoff-api-service:8082"
