apiVersion: v1
kind: ConfigMap
metadata:
  name: lissa-trading-user-service-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://lissa-trading-db:5432/lissa-trading-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_DEFAULT_SCHEMA: "user_service_db"

  SPRING_RABBITMQ_HOST: "lissa-trading-rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"

  AUTH_SERVICE_URL: "http://lissa-trading-auth-service:8081"

  TINKOFF_API_SERVICE_URL: "http://lissa-trading-tinkoff-api-service:8082"
  TINKOFF_API_SERVICE_TOKEN: "ZEdsdWEyOW1aa0Z3YVMxcGJuUmxjbTVoYkMxclpYaz0K"

  MOEX_API_SERVICE_URL: "http://lissa-trading-moex-api-service:8086"
  MOEX_API_SERVICE_TOKEN: "Ylc5bGVFRndhUzFwYm5SbGNtNWhiQzFyWlhrPQ=="
