apiVersion: v1
kind: ConfigMap
metadata:
  name: lissa-trading-user-service-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://lissa-trading-db:5432/lissa-trading-db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATA_DEFAULT_SCHEMA: "user_service_db"

  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "lissa_user"
  SPRING_RABBITMQ_PASSWORD: "secure_password"

  AUTH_SERVICE_URL: "http://lissa-trading-auth-service:8081"
  TINKOFF_API_SERVICE_URL: "http://lissa-trading-tinkoff-api-service:8082"
  LOKI_URL: "http://loki:3100"
  ZIPKIN_URL: "http://103.249.132.74:9411/api/v2/spans"
  MOEX_API_SERVICE_URL: "http://lissa-trading-moex-api-service:8086"