apiVersion: apps/v1
kind: Deployment
metadata:
  name: lissa-trading-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lissa-trading-user-service
  template:
    metadata:
      labels:
        app: lissa-trading-user-service
    spec:
      containers:
        - name: user-service
          image: belaquaaa/lissa-trading-user-service:latest # Замените на ваше имя образа
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: lissa-trading-user-service-config
            - secretRef:
                name: lissa-trading-user-service-secret
