apiVersion: v1
kind: Service
metadata:
  name: lissa-trading-user-service
spec:
  selector:
    app: lissa-trading-user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
