# GitHub Actions Workflow for Java with Maven using Java 17
# Incorporates modern best practices and optimizations

name: Java CI

on:
  push:
    branches: [main]
    paths:
      - '**.java'
      - '**.xml'
      - 'pom.xml'
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - '**.java'
      - '**.xml'
      - 'pom.xml'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 17 and cache Maven dependencies
      - name: Set up JDK 17 and cache dependencies
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      # Build and test the project with Maven
      - name: Build and test with Maven
        run: mvn -B clean verify

      # Upload test results for analysis
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/target/surefire-reports/*'

      # Upload code coverage reports
      - name: Upload code coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: '**/target/site/jacoco/*'

      # Archive built artifacts
      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: '**/target/*.jar'
